# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ci.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(529, 472)
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 480, 419))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lb_titulo = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lb_titulo.setFont(font)
        self.lb_titulo.setObjectName("lb_titulo")
        self.verticalLayout.addWidget(self.lb_titulo)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gl_fecha_nacimiento = QtWidgets.QGridLayout()
        self.gl_fecha_nacimiento.setObjectName("gl_fecha_nacimiento")
        self.lb_fn_dia = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb_fn_dia.setObjectName("lb_fn_dia")
        self.gl_fecha_nacimiento.addWidget(self.lb_fn_dia, 0, 0, 1, 1)
        self.lb_fn_anio = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb_fn_anio.setObjectName("lb_fn_anio")
        self.gl_fecha_nacimiento.addWidget(self.lb_fn_anio, 0, 2, 1, 1)
        self.lb_fn_mes = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb_fn_mes.setObjectName("lb_fn_mes")
        self.gl_fecha_nacimiento.addWidget(self.lb_fn_mes, 0, 1, 1, 1)
        self.sp_fn_anio = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.sp_fn_anio.setObjectName("sp_fn_anio")
        self.gl_fecha_nacimiento.addWidget(self.sp_fn_anio, 2, 2, 1, 1)
        self.sp_fn_mes = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.sp_fn_mes.setObjectName("sp_fn_mes")
        self.gl_fecha_nacimiento.addWidget(self.sp_fn_mes, 2, 1, 1, 1)
        self.sp_fn_dia = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.sp_fn_dia.setObjectName("sp_fn_dia")
        self.gl_fecha_nacimiento.addWidget(self.sp_fn_dia, 2, 0, 1, 1)
        self.gridLayout.addLayout(self.gl_fecha_nacimiento, 5, 3, 1, 1)
        self.lb_fecha_nacimiento = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb_fecha_nacimiento.setObjectName("lb_fecha_nacimiento")
        self.gridLayout.addWidget(self.lb_fecha_nacimiento, 5, 1, 1, 1)
        self.lb_nombres = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb_nombres.setObjectName("lb_nombres")
        self.gridLayout.addWidget(self.lb_nombres, 2, 1, 1, 1)
        self.le_nombres = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.le_nombres.setObjectName("le_nombres")
        self.gridLayout.addWidget(self.le_nombres, 2, 3, 1, 1)
        self.lb_apellidos = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb_apellidos.setObjectName("lb_apellidos")
        self.gridLayout.addWidget(self.lb_apellidos, 0, 1, 1, 1)
        self.le_apellidos = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.le_apellidos.setObjectName("le_apellidos")
        self.gridLayout.addWidget(self.le_apellidos, 0, 3, 1, 1)
        self.le_nacionalidad = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.le_nacionalidad.setObjectName("le_nacionalidad")
        self.gridLayout.addWidget(self.le_nacionalidad, 4, 3, 1, 1)
        self.lb_nacionalidad = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb_nacionalidad.setObjectName("lb_nacionalidad")
        self.gridLayout.addWidget(self.lb_nacionalidad, 4, 1, 1, 1)
        self.lb_sexo = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb_sexo.setObjectName("lb_sexo")
        self.gridLayout.addWidget(self.lb_sexo, 7, 1, 1, 1)
        self.cb_sexo = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cb_sexo.setObjectName("cb_sexo")
        self.cb_sexo.addItem("")
        self.cb_sexo.setItemText(0, "Elige tu sexo...")
        self.cb_sexo.addItem("")
        self.cb_sexo.addItem("")
        self.gridLayout.addWidget(self.cb_sexo, 7, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gl_display_info = QtWidgets.QGridLayout()
        self.gl_display_info.setContentsMargins(0, -1, -1, -1)
        self.gl_display_info.setObjectName("gl_display_info")
        self.lb_d_fecha_emision = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb_d_fecha_emision.setObjectName("lb_d_fecha_emision")
        self.gl_display_info.addWidget(self.lb_d_fecha_emision, 4, 0, 1, 1)
        self.lb_d_apellidos = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb_d_apellidos.setObjectName("lb_d_apellidos")
        self.gl_display_info.addWidget(self.lb_d_apellidos, 0, 0, 1, 1)
        self.lb_d_nombres = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb_d_nombres.setObjectName("lb_d_nombres")
        self.gl_display_info.addWidget(self.lb_d_nombres, 1, 0, 1, 1)
        self.lb_d_fecha_nacimiento = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb_d_fecha_nacimiento.setObjectName("lb_d_fecha_nacimiento")
        self.gl_display_info.addWidget(self.lb_d_fecha_nacimiento, 3, 0, 1, 1)
        self.lb_d_nacionalidad = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb_d_nacionalidad.setObjectName("lb_d_nacionalidad")
        self.gl_display_info.addWidget(self.lb_d_nacionalidad, 2, 0, 1, 1)
        self.lb_d_sexo = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb_d_sexo.setObjectName("lb_d_sexo")
        self.gl_display_info.addWidget(self.lb_d_sexo, 2, 1, 1, 1)
        self.lb_d_numero_documento = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb_d_numero_documento.setObjectName("lb_d_numero_documento")
        self.gl_display_info.addWidget(self.lb_d_numero_documento, 3, 1, 1, 1)
        self.lb_d_fecha_vencimiento = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb_d_fecha_vencimiento.setObjectName("lb_d_fecha_vencimiento")
        self.gl_display_info.addWidget(self.lb_d_fecha_vencimiento, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gl_display_info)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.btn_generar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_generar.setObjectName("btn_generar")
        self.verticalLayout.addWidget(self.btn_generar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 529, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lb_titulo.setText(_translate("MainWindow", "Rellene el Formulario para generar su carnet"))
        self.lb_fn_dia.setText(_translate("MainWindow", "Dia"))
        self.lb_fn_anio.setText(_translate("MainWindow", "Año"))
        self.lb_fn_mes.setText(_translate("MainWindow", "Mes"))
        self.lb_fecha_nacimiento.setText(_translate("MainWindow", "Fecha de Nacimiento"))
        self.lb_nombres.setText(_translate("MainWindow", "Nombres"))
        self.lb_apellidos.setText(_translate("MainWindow", "Apellidos"))
        self.lb_nacionalidad.setText(_translate("MainWindow", "Nacionalidad"))
        self.lb_sexo.setText(_translate("MainWindow", "sexo"))
        self.cb_sexo.setCurrentText(_translate("MainWindow", "Elige tu sexo..."))
        self.cb_sexo.setItemText(1, _translate("MainWindow", "Masculino"))
        self.cb_sexo.setItemText(2, _translate("MainWindow", "Femenino"))
        self.lb_d_fecha_emision.setText(_translate("MainWindow", "FECHA DE EMISIÓN\n"
"NONE"))
        self.lb_d_apellidos.setText(_translate("MainWindow", "APELLIDOS\n"
"NONE"))
        self.lb_d_nombres.setText(_translate("MainWindow", "NOMBRES\n"
"NONE"))
        self.lb_d_fecha_nacimiento.setText(_translate("MainWindow", "FECHA DE NACIMIENTO\n"
"NONE"))
        self.lb_d_nacionalidad.setText(_translate("MainWindow", "NACIONALIDAD\n"
"NONE"))
        self.lb_d_sexo.setText(_translate("MainWindow", "sexo\n"
"NONE"))
        self.lb_d_numero_documento.setText(_translate("MainWindow", "NÚMERO DOCUMENTO\n"
"NONE"))
        self.lb_d_fecha_vencimiento.setText(_translate("MainWindow", "FECHA DE VENCIMIENTO\n"
"NONE"))
        self.btn_generar.setText(_translate("MainWindow", "Generar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

