# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\calculator_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(418, 437)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 180, 361, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_9.setObjectName("btn_9")
        self.gridLayout.addWidget(self.btn_9, 2, 2, 1, 1)
        self.btn_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_7.setObjectName("btn_7")
        self.gridLayout.addWidget(self.btn_7, 2, 0, 1, 1)
        self.btn_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_8.setObjectName("btn_8")
        self.gridLayout.addWidget(self.btn_8, 2, 1, 1, 1)
        self.btn_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_6.setObjectName("btn_6")
        self.gridLayout.addWidget(self.btn_6, 1, 2, 1, 1)
        self.btn_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_4.setObjectName("btn_4")
        self.gridLayout.addWidget(self.btn_4, 1, 0, 1, 1)
        self.btn_igual = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_igual.setObjectName("btn_igual")
        self.gridLayout.addWidget(self.btn_igual, 4, 3, 1, 1)
        self.btn_cierra_parentesis = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_cierra_parentesis.setObjectName("btn_cierra_parentesis")
        self.gridLayout.addWidget(self.btn_cierra_parentesis, 3, 2, 1, 1)
        self.btn_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_1.setObjectName("btn_1")
        self.gridLayout.addWidget(self.btn_1, 0, 0, 1, 1)
        self.btn_resta = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_resta.setObjectName("btn_resta")
        self.gridLayout.addWidget(self.btn_resta, 2, 3, 1, 1)
        self.btn_suma = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_suma.setObjectName("btn_suma")
        self.gridLayout.addWidget(self.btn_suma, 1, 3, 1, 1)
        self.btn_multiplicacion = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_multiplicacion.setObjectName("btn_multiplicacion")
        self.gridLayout.addWidget(self.btn_multiplicacion, 3, 3, 1, 1)
        self.btn_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_5.setObjectName("btn_5")
        self.gridLayout.addWidget(self.btn_5, 1, 1, 1, 1)
        self.btn_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_2.setObjectName("btn_2")
        self.gridLayout.addWidget(self.btn_2, 0, 1, 1, 1)
        self.btn_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_3.setObjectName("btn_3")
        self.gridLayout.addWidget(self.btn_3, 0, 2, 1, 1)
        self.btn_abre_parentesis = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_abre_parentesis.setObjectName("btn_abre_parentesis")
        self.gridLayout.addWidget(self.btn_abre_parentesis, 3, 0, 1, 1)
        self.btn_ac = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_ac.setObjectName("btn_ac")
        self.gridLayout.addWidget(self.btn_ac, 0, 3, 1, 1)
        self.btn_division = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_division.setObjectName("btn_division")
        self.gridLayout.addWidget(self.btn_division, 4, 0, 1, 1)
        self.btn_division_entera = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_division_entera.setObjectName("btn_division_entera")
        self.gridLayout.addWidget(self.btn_division_entera, 4, 1, 1, 1)
        self.btn_modulo = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_modulo.setObjectName("btn_modulo")
        self.gridLayout.addWidget(self.btn_modulo, 4, 2, 1, 1)
        self.btn_0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_0.setObjectName("btn_0")
        self.gridLayout.addWidget(self.btn_0, 3, 1, 1, 1)
        self.lcd_resultado = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_resultado.setGeometry(QtCore.QRect(30, 80, 361, 81))
        self.lcd_resultado.setObjectName("lcd_resultado")
        self.lb_operacion = QtWidgets.QLabel(self.centralwidget)
        self.lb_operacion.setGeometry(QtCore.QRect(30, 10, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lb_operacion.setFont(font)
        self.lb_operacion.setText("")
        self.lb_operacion.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_operacion.setObjectName("lb_operacion")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_igual.setText(_translate("MainWindow", "="))
        self.btn_cierra_parentesis.setText(_translate("MainWindow", ")"))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_resta.setText(_translate("MainWindow", "-"))
        self.btn_suma.setText(_translate("MainWindow", "+"))
        self.btn_multiplicacion.setText(_translate("MainWindow", "*"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_abre_parentesis.setText(_translate("MainWindow", "("))
        self.btn_ac.setText(_translate("MainWindow", "AC"))
        self.btn_division.setText(_translate("MainWindow", "/"))
        self.btn_division_entera.setText(_translate("MainWindow", "//"))
        self.btn_modulo.setText(_translate("MainWindow", "%"))
        self.btn_0.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

